\input texinfo
@setfilename manual
@settitle SmartCalc v2.0
@documentencoding UTF-8

@copying
Copyright © 2024 by celestac
@end copying

@titlepage
@title Краткое руководство по функционалу калькулятора. Версия 2.0
@vskip 
@insertcopying
@author celestac
@end titlepage

@ifnottex
@node Top
@top SmartCalc v2.0
@insertcopying
@end ifnottex

@menu
* Базовая информация:: В этом разделе представлена ​​общая информация о калькуляторе.
* Арефметические операции:: В этом разделе перечислены арифметические операции, которые поддерживает калькулятор.
* Математические функции:: В этом разделе представлена ​​информация о списке реализованных математических функций.
* Построение графика функции:: В этом разделе представлена ​​информация о построении графиков функций.
* Кредитный калькулятор:: В этом разделе представлена ​​информация о возможностях кредитного калькулятора.
* Депозитный калькулятор:: В этом разделе представлена ​​информация о возможностях депозитного калькулятора.
* Коды ошибок:: В этом разделе представлена ​​информация о кодах ошибок и их расшифровки.
@end menu

@node Базовая информация
@chapter Базовая информация

Калькулятор разработан на языке программирования C++ с использованием QT версии 6.4.3. 
Основной принцип вычислений реализован на основе алгоритма Дейкстры, суть которого заключается в преобразовании математических выражений из инфиксной записи в обратную польскую запись.
Программа разрабатывалась и тестировалсь на ОС Ubuntu 22.04.3 LTS.

@node  Арефметические операции
@chapter  Арефметические операции

Калькулятор поддерживает следующие арифметические операции:
@enumerate
@item
Сложение: x + y
@item
Вычитание: x - y
@item
Умножение: x * y
@item
Деление: x / y
@item
Возведение в степень: x ^ y
@item
Остаток от деления: x mod y
@item
Унарный плюс: +x
@item
Унарный минус: -x
@end enumerate
После ввода выражения, необходимо нажать кнопку "=" для получения результата вычислений.

@node Математические функции
@chapter Математические функции

В калькуляторе реализованы следующие математические функции:
@enumerate
@item
cos(x)
@item
sin(x)
@item
tan(x)
@item
acos(x)
@item
asin(x)
@item
atan(x)
@item
sqrt(x)
@item
ln(x)
@item
log(x)
@end enumerate
После ввода выражения, необходимо нажать кнопку "=" для получения результата вычислений.

@node Построение графика функции
@chapter Построение графика функции

В калькуляторе реализована возможность построения графиков функций.
Для того чтобы построить график необходимо, чтобы в выражении присутствовала константа «Х».
Область определения и область значений функции ограничены как минимум числами от -1000000 до 1000000.
Для построения графика необходимо установить чек-бокс «Построить график».
После нажатия на "=" в правой части окна отобразиться график функций.
Реализована возможность самостоятельно выбирать область значения и область определения. А так же реализован автоматический режим расчета области значений.


@node Кредитный калькулятор
@chapter Кредитный калькулятор

Калькулятор имеет специальный режим работы: Кредитный калькулятор. Для его запуска нужно нажать кнопку "Кредитный калькулятор".

На вход подаются значения:

- Общая сумма кредита

- Срок

- Процентная ставка 

- Тип (аннуитетный, дифференцированный)

На выходе получаем: 

- Ежемесячный платеж

- Переплата по кредиту

- Общая выплата.


@node Депозитный калькулятор
@chapter Депозитный калькулятор

Калькулятор имеет специальный режим работы: Депозитный калькулятор. Для его запуска нужно нажать кнопку "Депозитный калькулятор".

На вход подаются значения:

- сумма вклада

- срок размещения

- процентная ставка

- налоговая ставка

- периодичность выплат

- капитализация процентов

- суммы пополнений и снятий

На выходе получаем: 

- начисленные проценты

- сумма налога

- сумма на вкладе к концу срока.


@node Коды ошибок
@chapter Коды ошибок

В случае возникновения ошибки, калькулятор возвращает текстовое описание ошибки.

Коды ошибок и их текстовое описание:

- Код 1 (kBadExpression): Не корретное выражение

- Код 2 (kBadBalanceBrackets): В выражении нарушен баланс скобок

- Код 3 (kEmpty): Строка-выражение пустая

- Код 4 (kTooShirt): Слишком короткое выражение (< 2 символов)

- Код 5 (kTooLong): Слишком длинное выражение (> 255 символов)

- Код 6 (kDivisionByZero): Ошибка деления на 0

- Код 7 (kCalculationError): Ошибка вычисления (например корень из отрицательного числа)

- Код 0 (kOk): Ошибок нет


@bye